version: '3'
#CMD: docker-compose up -d

services:

  postgres:
    image: postgres:15.3
    domainname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=article_generator
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server


