server:
  port: 8110

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1000000
        loggerLevel: basic


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: postgres
    url: jdbc:postgresql://localhost:5433/article_generator
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
    locations: classpath:db.migration
#
#springdoc:
#  swagger-ui:
#    path: /swagger.html